do not declare variables when using ||

diff --git a/calcardbackup b/calcardbackup
--- a/calcardbackup
+++ b/calcardbackup
@@ -22,7 +22,7 @@
 set -euo pipefail
 
 # calcardbackup version:
-version="0.4.2-10 (07.06.2018), AGPL-3.0"
+version="0.4.2-11 (07.06.2018), AGPL-3.0"
 
 ###
 ### BEGIN: FUNCTION DEFINITIONS
@@ -39,13 +39,14 @@ get_absolute_path() {
   # returns the absolute path to a given filepath which may be absolute or relative to a directory.
   # this is only needed and used for paths given by user via config-file (because config-file could be in a different dir from working dir or script dir)
   # arguments: ${1}=directory; ${2}=path to file (relative to ${1} or absolute)
+  local absolute_path
 
   if [[ "${2}" != /* ]]; then
     # change path of ${2} (file) relative to ${1} (dir) to absolute path and remove trailing slashes:
-    local absolute_path="$(readlink -f "${1}/${2}")" || error_exit "ERROR: ${1}/${2} can't be canonicalized. Check given path in config-file!"
+    absolute_path="$(readlink -f "${1}/${2}")" || error_exit "ERROR: ${1}/${2} can't be canonicalized. Check given path in config-file!"
   else
     # if ${2} contains already absolute path, then only remove trailing slashes:
-    local absolute_path="$(readlink -f "${2}")" || error_exit "ERROR: ${2} can't be canonicalized. Check given path in config-file!"
+    absolute_path="$(readlink -f "${2}")" || error_exit "ERROR: ${2} can't be canonicalized. Check given path in config-file!"
   fi
   echo "${absolute_path}"
 }
@@ -89,9 +90,11 @@ load_default_values() {
 
 read_config_file() {
   # reads calcardbackups config file (if passed with option -c or in case script is run with no option at all or only option -b)
+  local temp
 
   # absolute path to config file:
-  config_file="$(readlink -f "${config_file}")" || error_exit "ERROR: path to config file '${config_file}' can't be canonicalized." "Check given path!"
+  temp="$(readlink -f "${config_file}")" || error_exit "ERROR: path to config file '${config_file}' can't be canonicalized." "Check given path!"
+  config_file="${temp}"
   config_file_dir="$(dirname "${config_file}")"
   _output echo "+  Using configuration file ${config_file}, ignoring all other command line options."
   load_default_values # if more options have been passed to command: ignore all options except for -b
@@ -902,10 +905,11 @@ gpg_encrypt_backup() {
 delete_old_backups() {
   # deletes backups older than the configured amount of days ($delete_backups_older_than)
 
+  local deleted
   # delete backups older than $delete_backups_older_than days
   # (use option -daystart to set beginning of day = 0:00 am in order
   # to satisfy probably by users expected behavior of this function):
-  local deleted="$(find "${backupfolder}"/calcardbackup* -daystart -mtime +${delete_backups_older_than} -delete -exec echo "+     - " {} \;)" || error_exit "ERROR: deleting backups older than ${delete_backups_older_than} days produced above error."
+  deleted="$(find "${backupfolder}"/calcardbackup* -daystart -mtime +${delete_backups_older_than} -delete -exec echo "+     - " {} \;)" || error_exit "ERROR: deleting backups older than ${delete_backups_older_than} days produced above error."
 
   if [[ "${deleted}" != "" ]]; then
     # if there have been files deleted:
