redirect errors to stderr

diff --git a/calcardbackup b/calcardbackup
--- a/calcardbackup
+++ b/calcardbackup
@@ -43,10 +43,7 @@ function get_absolute_path() {
 function check_readable_file() {
   # checks if argument-1 is a file and readable. Argument-2 is error message if not.
   if [ ! -f "$1" ] || [ ! -r "$1" ]; then
-    echo "--"
-    echo "-- ERROR: Can't read ${2}"
-    echo "-- I need to be able to read ${1}"
-    error_exit
+    error_exit "ERROR: Can't read ${2}" "I need to be able to read ${1}"
   fi
 }
 
@@ -58,9 +55,9 @@ function preparations {
   echo "+  Checking dependencies and preparing..."
 
   # check for package curl
-  which curl > /dev/null || { echo "--"; echo "-- ERROR: Package 'curl' is needed for running this script. Install with 'apt-get install curl' and run script again" && error_exit; }
+  which curl > /dev/null || { error_exit "ERROR: Package 'curl' is needed for running this script. Install with 'apt-get install curl' and run script again"; }
   # check for package sed
-  which sed > /dev/null || { echo "--"; echo "-- ERROR: Package 'sed' is needed for running this script. Install with 'apt-get install sed' and run script again" && error_exit; }
+  which sed > /dev/null || { error_exit "ERROR: Package 'sed' is needed for running this script. Install with 'apt-get install sed' and run script again"; }
 
   # get path to scripts dir:
   actual_path=$(readlink -f "${BASH_SOURCE[0]}")
@@ -88,9 +85,7 @@ function preparations {
   # check config file for correct syntax (only comments, variable declarations and empty lines allowed)
   grep -E -qv '^([[:space:]]*|[[:space:]]*[a-z_]+="[^"]+"[[:space:]]*)(#.*)?$' "${config_path}/calcardbackup.conf"
   if [ "$?" -eq 0 ]; then
-    echo "-- ERROR: invalid config file! only variable-declarations, comments and empty lines allowed."
-    echo "-- Edit configuration file and run sript again."
-    error_exit
+    error_exit "ERROR: invalid config file! only variable-declarations, comments and empty lines allowed." "Edit configuration file and run sript again."
   else
     # config file is readable and has correct syntax. So let's include it now:
     . "${config_path}/calcardbackup.conf"
@@ -146,10 +141,7 @@ function preparations {
   if [ "$compression_method" == "zip" ]; then
     # check for package zip
     which zip > /dev/null || {
-      echo "--"
-      echo "-- ERROR: You chose to compress backed up files with 'zip' instead of 'tar.gz'."
-      echo "-- Therefore package 'zip' is needed. Install with 'apt-get install zip' and run script again"
-      error_exit
+      error_exit "ERROR: You chose to compress backed up files with 'zip' instead of 'tar.gz'." "Therefore package 'zip' is needed. Install with 'apt-get install zip' and run script again"
     }
   elif [ "${compression_method}" != "tar.gz" ]; then
     echo "-- NOTICE: Parameter 'compression_method' is not valid (only \"zip\" or \"tar.gz\" allowed)."
@@ -192,10 +184,7 @@ function read_config_php {
   minimumversion="5"
   davchangeversion="9"
   if [ "$mainversion" -lt "$minimumversion" ]; then
-    echo "--"
-    echo "-- ERROR: This script only works with versions >= 5.0."
-    echo "-- You are using Owncloud $version_config_php."
-    error_exit
+    error_exit "ERROR: This script only works with versions >= 5.0." "You are using Owncloud $version_config_php."
   elif [ "$mainversion" -ge "$davchangeversion" ]; then
     # Values for Nextcloud >= 9.0:
     caldav="dav"
@@ -235,10 +224,7 @@ function read_config_php {
     nextcloud_url=$nextcloud_url_overwrite
   elif [ "$nextcloud_url" == "$nextcloud_url_default" ] && [ "$nextcloud_url_overwrite" == "" ]; then
     # Error, if nextcloud_url is on default value and config.php contains no overwrite.cli.url (or is empty)
-    echo "--"
-    echo "-- ERROR: Can't retrieve url from ${configphp}"
-    echo "-- In your case nextcloud_url needs to be configured in config file ${config_path}/calcardbackup.conf"
-    error_exit
+    error_exit "ERROR: Can't retrieve url from ${configphp}" "In your case nextcloud_url needs to be configured in config file ${config_path}/calcardbackup.conf"
   elif [ "$nextcloud_url_overwrite" != "" ]; then
     # if overwrite.cli.uri is found (and nextcloud_url is on default value): use it as nextcloud_url
     nextcloud_url=$nextcloud_url_overwrite
@@ -271,9 +257,7 @@ function read_status_php {
   # Nextcloud 11.0.2 {"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"11.0.2.7","versionstring":"11.0.2","edition":"","productname":"Nextcloud"}
   grep -E -q '^\{"installed":"?(true|false)"?,("maintenance":"?(true|false)"?,("needsDbUpgrade":"?(true|false)"?,)?)?"version":"[[:digit:]]{1,2}\.[[:digit:]]\.[[:digit:]]{1,2}(\.[[:digit:]]{1,2})?","versionstring":"[[:digit:]]{1,2}\.[[:digit:]]\.[[:digit:]]{1,2}","edition":"[^"]*"(,"productname":"(ownCloud|Nextcloud)")?\}$' <<< $status_php
   if [ $? != 0 ]; then
-    echo "--"
-    echo "-- ERROR: No Own-/Nextcloud Installation found at ${nextcloud_url} !"
-    error_exit
+    error_exit "ERROR: No Own-/Nextcloud Installation found at ${nextcloud_url} !"
   fi
 
   # get version from status.php:
@@ -310,27 +294,16 @@ function read_status_php {
 
   # check whether version of config.php is the same than version of status.php
   if [ "$version_status_php" != "$version_config_php" ]; then
-    echo "--"
-    echo "-- ERROR: different versions detected:"
-    echo "-- ${productname} ${version_status_php} found at ${nextcloud_url}"
-    echo "-- ${productname} ${version_config_php} found at ${nextcloud_path}"
-    echo "-- check configured url and path in config file '${config_path}/calcardbackup.conf'"
-    error_exit
+    error_exit "ERROR: different versions detected:" "${productname} ${version_status_php} found at ${nextcloud_url}" "${productname} ${version_config_php} found at ${nextcloud_path}" "check configured url and path in config file '${config_path}/calcardbackup.conf'"
   fi
 
   # check for installed=true (and maintenance=false for versions >=8) in status.php
   grep -E -q '"installed":"?true"?' <<< $status_php || {
-    echo "--"
-    echo "-- ERROR: ${nextcloud_url}/status.php does not contain \"installed\":\"true\"!"
-    echo "-- You need to check your ${productname} Installation!"
-    error_exit
+    error_exit "ERROR: ${nextcloud_url}/status.php does not contain \"installed\":\"true\"!" "You need to check your ${productname} Installation!"
   }
   if [ "$mainversion" -ge 8 ]; then
     grep -E -q '"maintenance":"?false"?' <<< $status_php || {
-    echo "--"
-    echo "-- ERROR: ${productname} is in maintenance mode!"
-    echo "-- Disable maintenance mode with command \"sudo -u www-data php ${nextcloud_path}/occ maintenance:mode --off\" and run script again"
-    error_exit
+    error_exit "ERROR: ${productname} is in maintenance mode!" "Disable maintenance mode with command \"sudo -u www-data php ${nextcloud_path}/occ maintenance:mode --off\" and run script again"
     }
   fi
 }
@@ -350,8 +323,7 @@ function get_database_details {
     sqlite3)
       # check if command-line-interface of sqlite3 is installed:
       which sqlite3 > /dev/null || {
-        echo "--"
-        echo "-- ERROR: ${productname} database is sqlite3. Therefore this script requires package 'sqlite3'. Install with 'apt-get install sqlite3' and run script again" && error_exit
+        error_exit "ERROR: ${productname} database is sqlite3. Therefore this script requires package 'sqlite3'." "Install with 'apt-get install sqlite3' and run script again"
       }
       datadirectory=$(getvalue_from_configphp "datadirectory")
       sqlite3_database="${datadirectory}/owncloud.db"
@@ -360,10 +332,7 @@ function get_database_details {
       check_readable_file "${sqlite3_database}" "${productname}s SQLite3 database."
     ;;
     *)
-      echo "--"
-      echo "-- ERROR: Unsupported Database type: $dbtype"
-      echo "-- Only MySQL/MariaDB and SQLite3 are supported."
-      error_exit
+      error_exit "ERROR: Unsupported Database type: ${dbtype}" "Only MySQL/MariaDB and SQLite3 are supported."
     ;;
   esac
   echo "+  Database of chosen ${productname} installation is ${database}."
@@ -383,16 +352,12 @@ function create_backup_folder {
   # create backup folder:
   mkdir -p "$backupfolder"
   if [ ! $? -eq 0 ]; then
-    echo "--"
-    echo "-- ERROR: Backupfolder could not be created."
-    error_exit
+    error_exit "ERROR: Backupfolder could not be created."
   fi
 
   # check if backupfolder is writable
   if [ ! -w "$backupfolder" ]; then
-    echo "--"
-    echo "-- ERROR: Backupfolder is not writable."
-    error_exit
+    error_exit "ERROR: Backupfolder is not writable."
   fi
   day=$(date +"${backupfile_date_extension}")
   backupfolder_day="${backupfolder}/calcardbackup${day}"
@@ -464,10 +429,8 @@ function get_calendars {
         # check for ics-header in received file:
         if [ ! $(head -n1 "${backupfolder_day}/${principal[$i]}-${filename}.ics" | grep "BEGIN:VCALENDAR") ]; then
           mv "${backupfolder_day}/${principal[$i]}-${filename}.ics" "${backupfolder_day}/${principal[$i]}-${filename}.ics-ERROR.txt"
-          printf "\n--\n-- ERROR: the saved file is not a valid calendar-file. Something went wrong.\n"
-          echo "-- My guess: either wrong configured URL to ${productname} or a wrong combination of username/password in users.txt."
-          echo "-- You may also want to check the saved file for any hints what went wrong: ${backupfolder_day}/${principal[$i]}-${filename}.ics-ERROR.txt"
-          error_exit
+          printf "\n"
+          error_exit "ERROR: the saved file is not a valid calendar-file. Something went wrong." "My guess: either wrong configured URL to ${productname} or a wrong combination of username/password in users.txt." "You may also want to check the saved file for any hints what went wrong: ${backupfolder_day}/${principal[$i]}-${filename}.ics-ERROR.txt"
         fi
         exported=$((exported + 1))
         printf "...success!\n"
@@ -478,10 +441,7 @@ function get_calendars {
 
   # there is no matching Nextcloud user, if no calendar has been exported.
   if [ $exported == 0 ]; then
-    echo "--"
-    echo "-- ERROR: no match between given users in file 'users.txt' and registered ${productname} users!"
-    echo "-- You need to check '${userstxt_path}/users.txt'!"
-    error_exit
+    error_exit "ERROR: no match between given users in file 'users.txt' and registered ${productname} users!" "You need to check '${userstxt_path}/users.txt'!"
   fi
 }
 
@@ -552,10 +512,8 @@ function get_addressbooks {
         # check for vcf-header in received file:
         if [ ! $(head -n1 "${backupfolder_day}/${principal[$i]}-${filename}.vcf" | grep "BEGIN:VCARD") ]; then
           mv "${backupfolder_day}/${principal[$i]}-${filename}.vcf" "${backupfolder_day}/${principal[$i]}-${filename}.vcf-ERROR.txt"
-          printf "\n--\n-- ERROR: the saved file is not a valid vcard-file. Something went wrong.\n"
-          echo "-- My guess: either wrong configured URL to ${productname} or a wrong combination of username/password in users.txt."
-          echo "-- You may also want to check the saved file for any hints what went wrong: ${backupfolder_day}/${principal[$i]}-${filename}.vcf-ERROR.txt"
-          error_exit
+          printf "\n"
+          error_exit "ERROR: the saved file is not a valid vcard-file. Something went wrong." "My guess: either wrong configured URL to ${productname} or a wrong combination of username/password in users.txt." "You may also want to check the saved file for any hints what went wrong: ${backupfolder_day}/${principal[$i]}-${filename}.vcf-ERROR.txt"
         fi
         printf "...success!\n"
         break
@@ -591,19 +549,13 @@ function pack_it {
   if [ "${compression_method}" == "zip" ]; then
     # zip folder with backed up files:
     zip -r -q -${compression_level} "calcardbackup${day}.zip" "calcardbackup${day}"
-    if [ $? -ne 0 ]; then { compress_error="1"; }
-    fi
+    [ $? -eq 0 ] || compress_error="1"
   else
     # use tar.gz to compress backed up files (piped to gzip to be able to use compression_level):
     tar -c "calcardbackup${day}" | gzip -f -${compression_level} > "calcardbackup${day}.tar.gz"
-    if [ $? -ne 0 ]; then { compress_error="1"; }
-    fi
+    [ $? -eq 0 ] || compress_error="1"
   fi
-  if [ "$compress_error" == "1" ]; then
-    echo "--"
-    echo "-- ERROR: Compressing the files produced an error. See lines right above."
-    error_exit
-  fi
+  [ "$compress_error" == "1" ] && error_exit "ERROR: Compressing the files produced an error. See lines right above."
   cd "$working_dir"
   rm -r "$backupfolder_day"
   echo "+  Backup successfully compressed!"
@@ -614,8 +566,8 @@ function delete_old_backups {
   if [ "$delete_backups_older_than" -ge 1 ]; then
     deleted=$(find "${backupfolder}"/calcardbackup-* -type f -mtime +${delete_backups_older_than} -delete -exec echo "+   " {} \;)
     if [ "$?" -ne 0 ]; then
-      printf "\n-- ERROR: deleting backups older than ${delete_backups_older_than} days produced above error.\n"
-      error_exit
+      printf "\n"
+      error_exit "ERROR: deleting backups older than ${delete_backups_older_than} days produced above error."
     elif [ "$deleted" != "" ]; then
       echo "+  Those backups older than ${delete_backups_older_than} days have been deleted:"
       echo "${deleted}"
@@ -649,31 +601,27 @@ function plus_line {
 
 function curl_error {
   if [ $err -eq 6 ]; then
-    echo "--"
-    echo "-- ERROR: Curl error 6: could not resolve host ${nextcloud_url}."
     if [ "$nextcloud_url" == "$nextcloud_url_overwrite" ]; then
-      echo "-- Either that host is temporarily unavailable or 'overwrite.cli.uri' in ${configphp} is wrong."
+      problem="Either that host is temporarily unavailable or 'overwrite.cli.uri' in ${configphp} is wrong."
     else
-      echo "-- Either that host is temporarily unavailable or nextcloud_url in '${config_path}/calcardbackup.conf' is wrong."
+      problem="Either that host is temporarily unavailable or nextcloud_url in '${config_path}/calcardbackup.conf' is wrong."
     fi
-    error_exit
+    error_exit "ERROR: Curl error 6: could not resolve host ${nextcloud_url}." "${problem}"
   elif [ $err -eq 60 ]; then
-    echo "--"
-    echo "-- ERROR: Curl error 60: cannot authenticate peer certificate with known CA certificates."
-    echo "-- You need to configure trustful_certificate=\"no\" in config file '${config_path}/calcardbackup.conf'"
-    error_exit
+    error_exit "ERROR: Curl error 60: cannot authenticate peer certificate with known CA certificates." "You need to configure trustful_certificate=\"no\" in config file '${config_path}/calcardbackup.conf'"
   fi
-  echo "--"
-  echo "-- ERROR: Curl cannot get the requested file. This can have various reasons."
-  echo "-- For clarification lookup Curl Error number $err"
-  error_exit
+  error_exit "ERROR: Curl cannot get the requested file. This can have various reasons." "For clarification lookup Curl Error number $err"
 }
 
-function error_exit {
-  echo "-- Exiting."
-  echo "--"
-  echo "-------------  Errors occured. See messages above!  -------------"
-  echo
+function error_exit() {
+  echo "--" >&2
+  for message in "$@"; do
+    echo "-- ${message}" >&2
+  done
+  echo "-- Exiting." >&2
+  echo "--" >&2
+  echo "-------------  Errors occured. See messages above!  -------------" >&2
+  echo >&2
   exit 1
 }
 
